FILES = top.sv root.sv adder.v alu_input_stage.v alu_output_stage.v holdreg.v mux_out.v priority.v shifter.v calc2_if.sv Master.sv Monitor.sv Transaction.sv Rslt.sv Generator.sv tests/test.sv calc2_top.v
TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI