FILES = top.sv root.sv adder.v alu_input_stage.v alu_output_stage.v holdreg.v mux_out.v priority.v shifter.v calc_if.sv calc_master.sv calc_monitor.sv calc_request.sv calc_result.sv request_gen.sv tests/test.sv calc2_top.v
TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI