FILES =  adder.v alu_input_stage.v alu_output_stage.v holdreg.v mux_out.v priority.v shifter.v  testbench.sv apb_trans.sv apb_master.sv apb_if.sv apb_gen.sv apb_monitor.sv env.sv scoreboard.sv root.sv calc2_top.v 
TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI