FILES =  hdl/adder.v hdl/alu_input_stage.v hdl/alu_output_stage.v hdl/holdreg.v hdl/mux_out.v hdl/priority.v hdl/shifter.v tests/test_00_debug.sv tests/test_01_directed.sv tests/test_02_constrained.sv tests/test_03_cvr_driven.sv apb_env/apb_trans.sv apb_env/apb_master.sv apb_env/apb_if.sv apb_env/apb_gen.sv apb_env/apb_monitor.sv env/env.sv env/scoreboard.sv hdl/root.sv hdl/calc2_top.v 
TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI