FILES = hdl/top.sv hdl/root.sv hdl/mem.sv env/env.sv env/scoreboard.sv apb_env/apb_trans.sv apb_env/apb_master.sv apb_env/apb_if.sv apb_env/apb_gen.sv apb_env/apb_monitor.sv tests/test_00_debug.sv tests/test_01_directed.sv tests/test_02_constrained.sv tests/test_03_cvr_driven.sv

TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI