FILES = top.sv hdl/root.sv adder.v alu_input_stage.v alu_output_stage.v holdreg.v mux_out.v priority.v shifter.v Calc_env/calc_if.sv Calc_env/calc_master.sv Calc_env/calc_monitor.sv Calc_env/calc_request.sv Calc_env/calc_result.sv Calc_env/request_gen.sv tests/test.sv calc2_top.v
TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI