FILES = hdl/top.sv hdl/root.sv hdl/mem.sv tests/test.sv apb_env/apb_trans.sv apb_env/apb_master.sv apb_env/apb_if.sv apb_env/apb_gen.sv apb_env/apb_monitor.sv env/env.sv env/scoreboard.sv
TOPLEVEL = top 

include Makefiles/non_DPI/Makefile_non_DPI
